const express = require('express');
const router = express.Router();
const hgController = require('../controllers/hgController');
const { protect, checkCredits } = require('../middlewares/authMiddleware');
const { uploadSingleImage } = require('../middlewares/uploadMiddleware'); // Use centralized multer middleware

// POST /api/hg/generate - Generate an image
// Chain of middlewares: protect -> checkCredits -> multer upload -> controller
router.post(
  '/generate',
  protect,          // 1. Authenticate user
  checkCredits,     // 2. Check if user has enough credits
  uploadSingleImage('image'), // 3. Handle single image upload (field name 'image')
  hgController.generateImage // 4. Process the request
);

// GET /api/hg/ - Get all images generated by the authenticated user
router.get(
  '/',
  protect,          // 1. Authenticate user
  hgController.getUserImages // 2. Fetch images for the user
);

module.exports = router;
